version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - mvn clean
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - java -jar target/TestProject-1.0-SNAPSHOT.jar
artifacts:
  files:
    - target/TestProject-1.0-SNAPSHOT.jar